## Minimal project metadata for local builds (module location)
# This file is normally generated by CI or project tooling. Provide
# defaults here to allow local configure/build for debugging.

function(generate_dex_project_metafiles)
    # No-op for local builds
endfunction()

# Basic project metadata defaults
set(DEX_PROJECT_NAME "litecoincashdex")
set(DEX_API "mm2_cheetah")
set(DEX_RPC "127.0.0.1")
set(DEX_RPCPORT "7783")
set(DEX_DISPLAY_NAME "Litecoin Cash DEX")
set(DEX_SUPPORT_PAGE "https://example.com/support")
set(DEX_DISCORD "https://discord.example.com")
set(DEX_TWITTER "https://twitter.example.com")
set(DEX_PRIMARY_COIN "LTC")
set(DEX_SECOND_PRIMARY_COIN "BCH")
set(DEX_COMPANY_NAME "Example Company")
set(DEX_VERSION "0.9.8")
set(DEX_REPOSITORY_OWNER "owner")
set(DEX_REPOSITORY_NAME "repo")
set(DEX_CHECKSUM_API_URL "https://example.com/checksum")
set(DEX_APPDATA_FOLDER "atomicdex")
